# Generated by Django 5.0.2 on 2024-02-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(related_name='lessons', to='course.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='total_time',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
