# Generated by Django 5.0.2 on 2024-02-21 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_lesson_course_alter_lesson_total_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonuser',
            name='has_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_bought',
            field=models.ManyToManyField(blank=True, related_name='buyers', to=settings.AUTH_USER_MODEL),
        ),
    ]
